## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc

TYPE_CHECKER = src/TypeChecker/CheckerTypes.hs src/TypeChecker/CheckerUtils.hs src/TypeChecker/GrammarChecker.hs src/TypeChecker/TypeChecker.hs
GRAMMAR_FILES = src/Grammar/Abs.hs src/Grammar/Lex.hs src/Grammar/Par.hs
INTERPRETER_FILES = src/EvalExec.hs src/Evaluator.hs src/Interpreter.hs src/Utils.hs src/Types.hs src/Expr.hs src/Program.hs

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : interpreter

# Rules for building the parser.

interpreter : 
	${GHC} ${GHC_OPTS} ${GRAMMAR_FILES} ${TYPE_CHECKER} ${INTERPRETER_FILES} src/Main.hs -o interpreter
	rm -f src/*.hi src/*.o
	rm -f src/TypeChecker/*.hi src/TypeChecker/*.o
	rm -f src/Grammar/*.hi src/Grammar/*.o


# Rules for cleaning generated files.

clean :
	-rm -f interpreter

# distclean : clean
# 	-rm -f Grammar/Abs.hs Grammar/Abs.hs.bak Grammar/ComposOp.hs Grammar/ComposOp.hs.bak Grammar/Doc.txt Grammar/Doc.txt.bak Grammar/ErrM.hs Grammar/ErrM.hs.bak Grammar/Layout.hs Grammar/Layout.hs.bak Grammar/Lex.x Grammar/Lex.x.bak Grammar/Par.y Grammar/Par.y.bak Grammar/Print.hs Grammar/Print.hs.bak Grammar/Skel.hs Grammar/Skel.hs.bak Grammar/Test.hs Grammar/Test.hs.bak Grammar/XML.hs Grammar/XML.hs.bak Grammar/AST.agda Grammar/AST.agda.bak Grammar/Parser.agda Grammar/Parser.agda.bak Grammar/IOLib.agda Grammar/IOLib.agda.bak Grammar/Main.agda Grammar/Main.agda.bak Grammar/Grammar.dtd Grammar/Grammar.dtd.bak Grammar/Test Grammar/Lex.hs Grammar/Par.hs Grammar/Par.info Grammar/ParData.hs Makefile
# 	-rmdir -p Grammar/

# EOF
